### ISSUE TITLE
Initial State for Like Hearts

### ISSUE THREAD

**Issue by jon-wehner** [TolulopeVerissimo/InstantaneousGramme#84]
On initial load of the app, if a post is already liked, clicking the heart to unlike doesn't work. The heart briefly disappears and comes back. On the next click, the feature appears to work as intended.

**Comment by r-maloney** [comment]
Okay, let me look into it- what version are you seeing that on? I tried it on the heroku site and on the current master and I can't replicate the bug.

**Comment by jon-wehner** [comment]
I can't seem to make it happen again either.
